spring.application.name=passwordle-backend
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Security Secrets (Override these with Environment Variables in Production)
GATEWAY_SECRET=T3pKr%dC&amp;aj9
APP_API_KEY=xzj2jg@%7ZAw

# AWS & DynamoDB
aws.region=us-east-1
dynamodb.table.daily-levels=password-quest-prod-daily-levels
